name: run-tests

on: [push]

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test
        working-directory: tests
        run: bazel test --@rules_go//go/config:race --@rules_go//go/config:pure=false //...
